### ISSUE TITLE
Enable master branch protection

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/disco-to-proto3-converter#2]
This repository does not seem to have master branch
          protection enabled, at least in the way I'm expecting.
          I was hoping for:

          - master branch protection
          - requiring at least one code reviewer
          - requiring at least two status checks
          - enforcing rules for admins

          Please turn it on!

**Comment by SurferJeffAtGoogle** [comment]
Vadym, do you maintain this repo?

**Comment by vam-google** [comment]
@SurferJeffAtGoogle I guess so. It is a new repo that I created recently.

**Comment by SurferJeffAtGoogle** [comment]
Will you enable master branch protection?

**Comment by vam-google** [comment]
I will, looks like it is a requirement now. This repo is technically not even in Alpha yet, that is why I was not prioritizing this task. If it blocks yoshi I will prioritize it.

**Comment by SurferJeffAtGoogle** [comment]
Thanks Vadym.  We have a Q3 KR to enable branch protection for all
googleapis/ repos, so please prioritize it accordingly.

**Comment by JustinBeckwith** [comment]
Looks to be done
